{"name": "Test Failed Login", "status": "passed", "description": "Verifica que el método login devuelve False y no establece una sesión cuando se proporcionan credenciales inválidas.", "attachments": [{"name": "stdout", "source": "1759297d-1c02-494f-aab9-5b2c9e8f2a9b-attachment.txt", "type": "text/plain"}], "start": 1744782967617, "stop": 1744782967617, "uuid": "e88bb9e8-7a25-4017-8a95-3dacf766ae85", "historyId": "c550b0a351dea7d4620897e30646eab6", "testCaseId": "c550b0a351dea7d4620897e30646eab6", "fullName": "tests.test_01_authentication#test_invalid_login", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "unit"}, {"name": "feature", "value": "Authentication System"}, {"name": "tag", "value": "authentication"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_01_authentication"}, {"name": "host", "value": "emanuelZuluaga"}, {"name": "thread", "value": "26332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_01_authentication"}]}