{"name": "Test Login with Invalid Types", "status": "passed", "description": "Verifica que el método login lanza ValueError cuando se proporcionan tipos de datos inválidos (no cadenas) para usuario o contraseña.", "attachments": [{"name": "stdout", "source": "23c821e7-989b-4adf-9e65-cdc06cb5130c-attachment.txt", "type": "text/plain"}], "start": 1744782967596, "stop": 1744782967596, "uuid": "02ba1ea0-0292-4d4b-a18b-d04c28e8f80a", "historyId": "78207cc044686c169c1a5eb643305764", "testCaseId": "78207cc044686c169c1a5eb643305764", "fullName": "tests.test_01_authentication#test_login_invalid_types", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "unit"}, {"name": "feature", "value": "Authentication System"}, {"name": "tag", "value": "authentication"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_01_authentication"}, {"name": "host", "value": "emanuelZuluaga"}, {"name": "thread", "value": "26332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_01_authentication"}]}