{"uid":"9142125307c2333e","name":"Test Data Analysis with Invalid Coordinates","fullName":"tests.test_03_analytics#test_analyze_data_invalid_coordinates","historyId":"3c70616944fdc813995976a7b501539d","time":{"start":1744782969019,"stop":1744782969031,"duration":12},"description":"Verifica que el método AnalizeData lanza ValueError para coordenadas inválidas (None). El módulo falla al reemplazar NaN por 0, lo que debería corregirse.","descriptionHtml":"<p>Verifica que el método AnalizeData lanza ValueError para coordenadas inválidas (None). El módulo falla al reemplazar NaN por 0, lo que debería corregirse.</p>\n","status":"failed","statusMessage":"Failed: DID NOT RAISE <class 'ValueError'>","statusTrace":"@allure.feature(\"Data Analytics System\")\n    @allure.title(\"Test Data Analysis with Invalid Coordinates\")\n    @allure.description(\"Verifica que el método AnalizeData lanza ValueError para coordenadas inválidas (None). El módulo falla al reemplazar NaN por 0, lo que debería corregirse.\")\n    @allure.tag(\"analytics\", \"unit\", \"edge\")\n    @allure.severity(Severity.MINOR)\n    def test_analyze_data_invalid_coordinates():\n        invalid_data = pd.DataFrame({\n            \"start_station_name\": [\"Station A\"],\n            \"end_station_name\": [\"Station B\"],\n            \"start_station_latitude\": [None],\n            \"start_station_longitude\": [5.32],\n            \"end_station_latitude\": [60.40],\n            \"end_station_longitude\": [5.33],\n            \"duration\": [300]\n        })\n    \n        with patch(\"pandas.read_excel\", return_value=invalid_data):\n            analytics = Analytics()\n>           with pytest.raises(ValueError):  # geodesic fallará con None\nE           Failed: DID NOT RAISE <class 'ValueError'>\n\ntests\\test_03_analytics.py:152: Failed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"Verifica que el método AnalizeData lanza ValueError para coordenadas inválidas (None). El módulo falla al reemplazar NaN por 0, lo que debería corregirse.","status":"failed","statusMessage":"Failed: DID NOT RAISE <class 'ValueError'>","statusTrace":"@allure.feature(\"Data Analytics System\")\n    @allure.title(\"Test Data Analysis with Invalid Coordinates\")\n    @allure.description(\"Verifica que el método AnalizeData lanza ValueError para coordenadas inválidas (None). El módulo falla al reemplazar NaN por 0, lo que debería corregirse.\")\n    @allure.tag(\"analytics\", \"unit\", \"edge\")\n    @allure.severity(Severity.MINOR)\n    def test_analyze_data_invalid_coordinates():\n        invalid_data = pd.DataFrame({\n            \"start_station_name\": [\"Station A\"],\n            \"end_station_name\": [\"Station B\"],\n            \"start_station_latitude\": [None],\n            \"start_station_longitude\": [5.32],\n            \"end_station_latitude\": [60.40],\n            \"end_station_longitude\": [5.33],\n            \"duration\": [300]\n        })\n    \n        with patch(\"pandas.read_excel\", return_value=invalid_data):\n            analytics = Analytics()\n>           with pytest.raises(ValueError):  # geodesic fallará con None\nE           Failed: DID NOT RAISE <class 'ValueError'>\n\ntests\\test_03_analytics.py:152: Failed","steps":[],"attachments":[{"uid":"44543dd54d0e907c","name":"stdout","source":"44543dd54d0e907c.txt","type":"text/plain","size":37}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false,"stepsCount":0},"afterStages":[],"labels":[{"name":"tag","value":"unit"},{"name":"tag","value":"edge"},{"name":"tag","value":"analytics"},{"name":"severity","value":"minor"},{"name":"feature","value":"Data Analytics System"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_03_analytics"},{"name":"host","value":"emanuelZuluaga"},{"name":"thread","value":"26332-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_03_analytics"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"minor","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[]}],"tags":["analytics","unit","edge"]},"source":"9142125307c2333e.json","parameterValues":[]}